/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ikasako.sudachi.perftest;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class RegexTest {
    public static void main(String[] args) throws Exception {
        long start = System.currentTimeMillis();
        for (int i=0;i<10000;i++) {
            new RegexTest().run("hoge");
        }
        System.out.println(System.currentTimeMillis() -start);
    }

    public void run(String str) {
        int length;
        while ((length = getEnd(str)) != 0) {
            str = str.substring(length);
        }
    }

    private int getEnd(String s) {
        final Pattern spaces = Pattern.compile(".+\\s+");
        Matcher m = spaces.matcher(s);
        if (m.find()) {
            return m.end();
        }
        return 0;
    }
}
