/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ikasako.sudachi.perftest;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class RegexTest {
    public static void main(String[] args) throws Exception {
        RegexTest instance = new RegexTest();

        String plainText = Files.readString(Path.of("app/src/main/resources", "sentences.txt"));
        System.out.println("plain text");
        instance.execute(plainText, 100);

        System.out.println("space separated text");
        String spaceStr = StringUtil.replaceOddChar(plainText, ' ');
        instance.execute(spaceStr, 100);

        System.out.println("newline separated text");
        String newLineStr = StringUtil.replaceOddChar(plainText, '\n');
        instance.execute(newLineStr, 100);
    }

    public void execute(String str, int times) {
        long start = System.currentTimeMillis();
        for (int i=0; i<times; i++) {
            run(str);
        }
        System.out.println(System.currentTimeMillis() -start);

    }

    private void run(String str) {
        int length;
        while ((length = getEnd(str)) != 0) {
            str = str.substring(length);
        }
    }

    private int getEnd(String s) {
        final Pattern spaces = Pattern.compile(".+\\s+");
        Matcher m = spaces.matcher(s);
        if (m.find()) {
            return m.end();
        }
        return 0;
    }
}
