/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ikasako.sudachi.perftest;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class RegexTest {
    public static void main(String[] args) throws Exception {
        RegexTest instance = new RegexTest();

        String plainText = Files.readString(Path.of("app/src/main/resources", "sentences.txt"));
        String spaceStr = StringUtil.replaceOddChar(plainText, ' ');
        System.out.println("space separated text. length:" + spaceStr.length());
        instance.execute(spaceStr, 100);

        spaceStr = StringUtil.amplification(spaceStr, 10);
        System.out.println("space separated text length:" + spaceStr.length());
        instance.execute(spaceStr, 100);

        String newLineStr = StringUtil.replaceOddChar(plainText, '\n');
        System.out.println("newline separated text length:" + newLineStr.length());
        instance.execute(newLineStr, 100);

        newLineStr = StringUtil.amplification(newLineStr, 10);
        System.out.println("newline separated text length:" + newLineStr.length());
        instance.execute(newLineStr, 100);
        
    }

    public void execute(String str, int times) {
        long start = System.currentTimeMillis();
        for (int i=0; i<times; i++) {
            run(str);
        }
        System.out.println(System.currentTimeMillis() - start + "ms");
        System.out.println("----------------------");

    }

    private void run(String str) {
        int length;
        while ((length = getEnd(str)) != 0) {
            str = str.substring(length);
        }
    }

    private int getEnd(String s) {
        final Pattern spaces = Pattern.compile(".+\\s+");
        Matcher m = spaces.matcher(s);
        if (m.find()) {
            return m.end();
        }
        return 0;
    }
}
